name: suno-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.8.0=pyhd8ed1ab_0
  - aom=3.9.1=hf036a51_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py311h3336109_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=25.1.0=pyh71513ae_0
  - audioread=3.0.1=py311h6eed73b_2
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=h00291cd_2
  - brotli-bin=1.1.0=h00291cd_2
  - brotli-python=1.1.0=py311hd89902b_2
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2025.1.31=h8857fd0_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.2=h950ec3b_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py311h137bacd_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py311h4e34fa0_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h0dc2134_0
  - dbus=1.13.6=h811a1a6_3
  - debugpy=1.8.13=py311hc356e98_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h240833e_0
  - ffmpeg=7.1.1=gpl_h5328504_100
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py311ha3cf9ac_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=h60636b9_2
  - fribidi=1.0.10=hbcb3906_0
  - gdk-pixbuf=2.42.12=ha587570_0
  - gettext=0.23.1=hd385c8e_0
  - gettext-tools=0.23.1=h27064b9_0
  - gmp=6.3.0=hf036a51_2
  - graphite2=1.3.13=h73e2aa4_1003
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=10.4.0=h86b413f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.0.0=pyhfb0248b_1
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py311h6eed73b_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py311hf2f7c97_0
  - krb5=1.21.3=h37d8d59_0
  - lame=3.100=hb7f2c08_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hb486fe8_0
  - libabseil=20240722.0=cxx17_h0e468a2_4
  - libasprintf=0.23.1=h27064b9_0
  - libasprintf-devel=0.23.1=h27064b9_0
  - libass=0.17.3=h07fa1ac_1
  - libblas=3.9.0=31_h7f60823_openblas
  - libbrotlicommon=1.1.0=h00291cd_2
  - libbrotlidec=1.1.0=h00291cd_2
  - libbrotlienc=1.1.0=h00291cd_2
  - libcblas=3.9.0=31_hff6cab4_openblas
  - libcxx=19.1.7=hf95d169_0
  - libdeflate=1.23=he65b83e_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libexpat=2.6.4=h240833e_0
  - libffi=3.4.6=h281671d_0
  - libflac=1.4.3=he965462_0
  - libgettextpo=0.23.1=h27064b9_0
  - libgettextpo-devel=0.23.1=h27064b9_0
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - libglib=2.82.2=h5c976ab_1
  - libhwloc=2.11.2=default_h4cdd727_1001
  - libiconv=1.18=h4b5e92a_1
  - libintl=0.23.1=h27064b9_0
  - libintl-devel=0.23.1=h27064b9_0
  - libjpeg-turbo=3.0.0=h0dc2134_1
  - liblapack=3.9.0=31_h236ab99_openblas
  - libllvm15=15.0.7=hc29ff6c_5
  - liblzma=5.6.4=hd471939_0
  - libogg=1.3.5=hfdf4475_0
  - libopenblas=0.3.29=openmp_hbf64a52_0
  - libopenvino=2025.0.0=hf0fe607_1
  - libopenvino-auto-batch-plugin=2025.0.0=h4464f52_1
  - libopenvino-auto-plugin=2025.0.0=h4464f52_1
  - libopenvino-hetero-plugin=2025.0.0=hf02614b_1
  - libopenvino-intel-cpu-plugin=2025.0.0=hf0fe607_1
  - libopenvino-ir-frontend=2025.0.0=hf02614b_1
  - libopenvino-onnx-frontend=2025.0.0=h40b3fd7_1
  - libopenvino-paddle-frontend=2025.0.0=h40b3fd7_1
  - libopenvino-pytorch-frontend=2025.0.0=hbcac03e_1
  - libopenvino-tensorflow-frontend=2025.0.0=hacd10b5_1
  - libopenvino-tensorflow-lite-frontend=2025.0.0=hbcac03e_1
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.47=h3c4a55f_0
  - libprotobuf=5.28.3=h6401091_1
  - librosa=0.10.2.post1=pyhd8ed1ab_1
  - librsvg=2.58.4=h21a6cfa_2
  - libsndfile=1.2.2=h9603cec_1
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.49.1=hdb6dae5_1
  - libtiff=4.7.0=hb77a491_3
  - libusb=1.0.27=h83ace79_100
  - libuv=1.50.0=h4cb831e_0
  - libvorbis=1.3.7=h046ec9c_0
  - libvpx=1.14.1=hf036a51_0
  - libwebp-base=1.5.0=h6cf52b4_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.13.6=hebb159f_0
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=19.1.7=ha54dae1_0
  - markupsafe=3.0.2=py311ha3cf9ac_1
  - matplotlib=3.10.1=py311h6eed73b_0
  - matplotlib-base=3.10.1=py311h19a4563_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.2=pyhd8ed1ab_0
  - mpg123=1.32.9=h78e78a4_0
  - msgpack-python=1.1.0=py311hf2f7c97_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - narwhals=1.29.1=pyhd8ed1ab_0
  - nb_conda=2.2.1=pyh707e725_7
  - nb_conda_kernels=2.5.1=pyh707e725_2
  - nbclassic=1.2.0=pyhd8ed1ab_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nodejs=22.13.0=hffbc63d_0
  - notebook=6.5.7=pyha770c72_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.61.0=py311h5322ac9_1
  - numpy=2.1.3=py311h14ed71f_0
  - openh264=2.6.0=h4883158_0
  - openjpeg=2.5.3=h7fd6d84_0
  - openssl=3.4.1=hc426f3f_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py311haeb46be_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.1=hf94f63b_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.44=h7634a1b_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h25da234_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h1fd1274_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - plotly=6.0.0=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py311h4d7f069_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h46091d4_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyobjc-core=11.0=py311hfbc4093_0
  - pyobjc-framework-cocoa=11.0=py311hfbc4093_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.11.11=h9ccd52b_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.11=5_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311ha3cf9ac_2
  - pyzmq=26.2.1=py311hb21797c_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h7cca4af_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.23.1=py311hab9d7c2_0
  - scikit-learn=1.6.1=py311h542f1db_0
  - scipy=1.15.2=py311h0c91ca8_0
  - sdl2=2.32.50=hc0cb955_1
  - sdl3=3.2.8=h6dd79e8_0
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=haf3c120_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - soxr=0.1.3=hbf74d83_3
  - soxr-python=0.5.0.post1=py311hd89902b_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.0.0=h240833e_0
  - tbb=2022.0.0=h0ec6371_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py311h4d7f069_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - unicodedata2=16.0.0=py311h4d7f069_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.5=h7130eaa_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hd23fc13_2
  - zstandard=0.19.0=py311h5547dcb_0
  - zstd=1.5.7=h8210216_1
  - pip:
      - cython==3.0.12
      - llvmlite==0.44.0
      - madmom==0.16.1
      - mido==1.3.3
      - pydub==0.25.1
prefix: /Users/steven/miniconda3/envs/suno-analytics
